language: cpp
env:
  global:
  - FORCE_INSTALL=1
  - HAS_OPENSSL_BUILD=1
  - HAS_OPENSSL_W32BUILD=0
  - WERROR=1

matrix:
  include:

  - os: osx
    name: "Build macOS XCODE5"
    osx_image: xcode10.2
    compiler: clang

    script:
    - HOMEBREW_NO_INSTALL_CLEANUP=1 HOMEBREW_NO_AUTO_UPDATE=1 brew install openssl mingw-w64
    - "./build_oc.tool"
    - "./build_duet.tool"

    deploy:
      provider: releases
      skip_cleanup: true
      file:
      - Binaries/*.zip
      file_glob: true
      on:
        tags: true
      api_key:
        secure: ZofF91SzCPE5n1iXOwaGs7RpMeOWPYohxhzl6rh8MFGWmYlbWLe+Sjpj8vIPkd/gjoRD4DKUszWdmh5FojYVO+CqBGurEVJo0lEU0fX7Mb+rn7+AXi4CdYF8bfD6SptDgbxCyj9ktgLeXEQ9cM6LPFdphVG91wL5aNP8/J2Xl6JPmNRdI6SoZ9fpl6N3kDCqskm8IEU0e/UrTYM9MdtKaDm6lPl/DABxOb6h/Paa116ofPKZjPqKnH+9iCcRfzawvIzPTKBD23KqlpEpR2YzNF/SFTHf9kJPQWVsuMBklNXauh+TtouvJNc8th96TVyHCVJt8UeHo1psSpL8EJp+kUWzWlOgAjiDgVPUmVPy8mVbYJTI8djEm2WrOs9DiaU1hAWIFXOzaYu9caRNLaKrXVKOcJe6lOsIXK/yUnP1lYh8+iSQStKFIV0jQ+swcobV8QqtztP1L44izUv+vccaQJCGw3vQYM3+HE2QE4xYA/Sqnt8sfy8Kq1jYZ1nG1niRhW6E9pE4KlbnxU2opXXfmjS3PGqjj+SJO0qGhraYrQSisJwBkMTFhyiJfiXusG+Up8npAQ5BiJl1GCiJ+sg1RE4c4pgTWl7LfhGjnjWTW9qQCaILiJrgbE8qDXIggzZgRccjU/Y5F7yWQ7D0kNiqY9nsL6P9Lr1pKp6LiOwXWnY=

  - os: linux
    name: "Build Linux CLANGPDB/GCC5"
    dist: xenial
    addons:
      apt:
        packages:
        - nasm
        - uuid-dev
        - libssl-dev

    script:
    - export PYTHON_COMMAND=python3 # Something is broken in Travis CI environment, it asks for python3.7.
    - file="clang+llvm-9.0.1-x86_64-linux-gnu-ubuntu-16.04"
    - suf=".tar.xz"
    - curl -LO "https://github.com/llvm/llvm-project/releases/download/llvmorg-9.0.1/${file}${suf}" || exit 1
    - sum=$(shasum -a 256 "${file}${suf}" | cut -f1 -d' ')
    - expsum="1af280e96fec62acf5f3bb525e36baafe09f95f940dc9806e22809a83dfff4f8"
    - if [ "$sum" != "$expsum" ]; then echo "Invalid checksum $sum" ; exit 1 ; fi
    - tar -xf "${file}${suf}" || exit 1
    - export PATH="$(pwd)/${file}/bin:$PATH"
    - "./build_oc.tool"
    - "./build_duet.tool"

  - os: linux
    name: "Build Linux CLANG38"
    dist: xenial
    addons:
      apt:
        packages:
        - nasm
        - uuid-dev
        - clang-8
        - llvm-8-dev

    script:
    - export PYTHON_COMMAND=python3 # Something is broken in Travis CI environment, it asks for python3.7.
    - sudo apt-get remove -y llvm-3.8 libllvm3.8 # Move LLVM 3.8 out of the way.
    - export PATH="/usr/lib/llvm-8/bin:$PATH" # Default compiler (7.0 or 3.8) has no LTO plugin.
    - export TOOLCHAINS=CLANG38
    - "./build_oc.tool"
    - "./build_duet.tool"
    # Currently this is too ugly, but maybe we can use that in the future.
    - sudo apt-get install -y doxygen texlive texlive-latex-extra
    - abort() { tail -200 log.txt ; exit 1 ; }
    - doxygen Doxyfile &> log.txt || abort
    - cd Doxy/latex || abort
    - make pdf &> log.txt || abort

  - os: windows
    name: "Build Windows VS2017"

    script:
    - HAS_OPENSSL_BUILD=0
    - choco install microsoft-build-tools visualcpp-build-tools make nasm python zip
    - "./build_oc.tool"
    - "./build_duet.tool"
